// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhkXK71l5IVPQQgNRYC-fMfitFxt_15Q',
    appId: '1:639193032500:web:6fad80ac802912c47ce761',
    messagingSenderId: '639193032500',
    projectId: 'fridge-bf293',
    authDomain: 'fridge-bf293.firebaseapp.com',
    databaseURL: 'https://fridge-bf293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fridge-bf293.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJH4IKbD9-HdjsppAuLqjnBikp39jX7WQ',
    appId: '1:639193032500:android:8f01d92a624a27747ce761',
    messagingSenderId: '639193032500',
    projectId: 'fridge-bf293',
    databaseURL: 'https://fridge-bf293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fridge-bf293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZENE7u07GcITAX7aSO6dR5sYN8RS-iNk',
    appId: '1:639193032500:ios:011f5532b48289b87ce761',
    messagingSenderId: '639193032500',
    projectId: 'fridge-bf293',
    databaseURL: 'https://fridge-bf293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fridge-bf293.appspot.com',
    iosBundleId: 'com.example.testrun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZENE7u07GcITAX7aSO6dR5sYN8RS-iNk',
    appId: '1:639193032500:ios:f2eb6eb96aa5d7337ce761',
    messagingSenderId: '639193032500',
    projectId: 'fridge-bf293',
    databaseURL: 'https://fridge-bf293-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fridge-bf293.appspot.com',
    iosBundleId: 'com.example.testrun.RunnerTests',
  );
}
